source/accounts/urls.py
from django.urls import path
from accounts.views import logout_view, login_view, register_view, \
    user_activate_view, UserDetailView, UserChangeView, UserChangePasswordView, UsersListView, password_reset_email_view, PasswordResetFormView

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('users/', UsersListView.as_view(), name='users_list'),
    path('reset-password/', password_reset_email_view, name='password_reset_email'),
    path('reset-password/<token>/', PasswordResetFormView.as_view(), name='password_reset_form')
]


app_name = 'accounts'

source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api.views import ProjectViewSet, TaskViewSet, LogoutView

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet)
router.register(r'tasks', TaskViewSet)



app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='obtain_token_auth'),
    path('logout/', LogoutView.as_view(), name='delete_auth-token'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, TaskView, TaskCreateView, TaskUpdateView, \
    TaskDeleteView, StatusesView, StatusCreateView, StatusUpdateView, StatusDeleteView, TypesView, TypeCreateView, \
    TypeUpdateView, TypeDeleteView, ProjectsView, ProjectView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView,\
    TeamDeleteView, ProjectUsersUpdateView

urlpatterns = [
    path('', ProjectsView.as_view(), name='index'),
    path('tasks/', IndexView),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('task/add-project/<int:pk>/', TaskCreateView.as_view(), name='task_add'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('status/', StatusesView.as_view(), name='statuses_view'),
    path('status/add/', StatusCreateView.as_view(), name='status_add'),
    path('status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update'),
    path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='status_delete'),
    path('type/', TypesView.as_view(), name='types_view'),
    path('type/add/', TypeCreateView.as_view(), name='type_add'),
    path('type/<int:pk>/update/', TypeUpdateView.as_view(), name='type_update'),
    path('type/<int:pk>/delete/', TypeDeleteView.as_view(), name='type_delete'),
    path('projects/', ProjectsView.as_view(), name='projects_view'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/update-users/', ProjectUsersUpdateView.as_view(), name='project_users_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('user_delete/<int:pk>/', TeamDeleteView.as_view(), name='user_delete_from_project'),
]


app_name = 'webapp'

source/accounts/models.py
from django.db import models
from uuid import uuid4
from django.contrib.auth.models import User


class Token(models.Model):
    token = models.UUIDField(verbose_name='token', default=uuid4)
    user = models.ForeignKey('auth.User', related_name='registration_tokens',
                             verbose_name='User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.token)


class Team(models.Model):
    user_key = models.ForeignKey('auth.User', related_name='team', on_delete=models.PROTECT)
    project_key = models.ForeignKey('webapp.Project', related_name='team', on_delete=models.PROTECT)
    started_at = models.DateField(null=True, blank=True, verbose_name='Started at')
    ended_at = models.DateField(null=True, blank=True, verbose_name='Ended at')

    def __str__(self):
        return str(self.user_key)


class Profile(models.Model):
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    about_user = models.TextField(null=True, blank=True, verbose_name='О себе')
    git_profile = models.URLField(null=True, blank=True, verbose_name='Ссылка на Git профиль')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, label='Username')
    first_name = forms.CharField(max_length=100, required=False, label='First name')
    last_name = forms.CharField(max_length=100, required=False, label='Last name')
    password = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput,
                               label='Password')
    password_confirm = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput,
                               label='Password confirm')
    email = forms.EmailField(required=True, label='Email')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('Username is already taken.', code='username_taken')
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('This email is already registered', code='registered_email')
        except User.DoesNotExist:
            return email

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match', code='password_do_not_match')
        if not (first_name or last_name):
            raise ValidationError('One of these First name or Last name fields should be filled')
        return self.cleaned_data


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    about_user = forms.CharField(required=False, label='About user', widget=forms.Textarea)
    git_profile = forms.URLField()

    def clean(self):
        super().clean()
        git_profile = self.cleaned_data.get('git_profile')
        git_link = 'https://github.com/'
        if git_profile.find(git_link, 0, 19):
            raise ValidationError('The link should be to Git profile')
        return self.cleaned_data

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.profile = self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if not profile.avatar:
            profile.avatar = None
        if commit:
            profile.save()
        return profile

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        profile_fields = ['avatar', 'about_user', 'git_profile']


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm']


class UserPasswordResetForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = []

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from main.settings import HOST_NAME
from django.views.generic import UpdateView, DetailView, ListView

from accounts.forms import SignUpForm, UserChangeForm, UserChangePasswordForm, UserPasswordResetForm
from accounts.models import Token, Profile


def send_token(user, subject, message, redirect_url):
    token = Token.objects.create(user=user)
    url = HOST_NAME + reverse(redirect_url, kwargs={'token': token})
    print(url)
    try:
        user.email_user(subject, message.format(url=url))
    except ConnectionRefusedError:
        print('Could not send email. Server error.')


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next', '')
            if next_url:
                return redirect(next_url)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'registration/login.html', context=context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'register.html', context={'form': form})
    elif request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = User(
                 username=form.cleaned_data.get('username'),
                 first_name=form.cleaned_data.get('first_name'),
                 last_name=form.cleaned_data.get('last_name'),
                 email=form.cleaned_data.get('email'),
                 is_active=False
            )
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            Profile.objects.create(user=user)
            token = Token.objects.create(user=user)

            activation_url = HOST_NAME + reverse('accounts:user_activate', kwargs={'token': token})
            print(activation_url)
            try:
                user.email_user(
                    'Вы зарегистрировались на сайте localhost:8000.',
                    'Для активации перейдите по ссылке: ' + activation_url
                )
            except ConnectionRefusedError:
                print('Could not send email. Server error.')

            return redirect('webapp:index')
        else:
            return render(request, 'register.html', context={'form': form})


def user_activate_view(request, token):
    token = get_object_or_404(Token, token=token)
    user = token.user
    user.is_active = True
    user.save()
    login(request, user)
    return redirect('webapp:index')


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    # def form_valid(self, form):
    #     user = form.save()
    #     login(self.request, user)
    #     return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:login')


class UsersListView(ListView):
    template_name = 'registration/users.html'
    context_object_name = 'users'
    model = User
    paginate_by = 4
    paginate_orphans = 1


def password_reset_email_view(request):
    if request.method == 'GET':
        return render(request, 'password_reset_email.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        users = User.objects.filter(email=email)
        if len(users) > 0:
            print('yes')
            user = users[0]
            send_token(user,
                       'Вы запросили восстановление пароля на сайте localhost:8000.',
                       'Для ввода нового пароля перейдите по ссылке: {url}',
                       redirect_url='accounts:password_reset_form')
        return render(request, 'password_reset_confirm.html')


class PasswordResetFormView(UpdateView):
    model = User
    template_name = 'password_reset_form.html'
    form_class = UserPasswordResetForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        token = self.get_token()
        return token.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['token'] = self.kwargs.get('token')
        return context

    def form_valid(self, form):
        token = self.get_token()
        print(token)
        token.delete()
        return super().form_valid(form)

    def get_token(self):
        token_value = self.kwargs.get('token')
        return get_object_or_404(Token, token=token_value)

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-center">
        <h1>Password reset</h1>
        <p>Email with instructions was sent to specified address.</p>
        <p><a href="{% url 'webapp:index' %}">Back Home</a></p>
    </div>
{% endblock %}

source/accounts/templates/password_reset_email.html
{% extends 'base.html' %}
{% block content %}
    <h1>Password reset</h1>
    <form action="{% url 'accounts:password_reset_email' %}" method="post" class="text-center">
        {% csrf_token %}
        <label for="email">Email: </label><input type="email" name="email" id="email">
        <input type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Password reset</h1>
    <form action="{% url 'accounts:password_reset_form' token %}" method="post" class="text-center">
        {% include 'partial/form.html' with button_text="Reset" %}
    </form>
{% endblock %}

source/accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <h1>Sign UP</h1>
    <form action="{% url 'accounts:register' %}" method="post" class="text-center">
        {% include 'partial/form.html' with button_text='Register' %}
    </form>
{% endblock %}

source/accounts/templates/uder_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit</a></li>
    <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Profile</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}"
             width="250" height="250" alt="user picture">
    {% endif %}
    <p>Username: <b>{{ user_obj.username }}</b></p>
    <p>First name: <b>{{ user_obj.first_name }}</b></p>
    <p>Last name: <b>{{ user_obj.last_name }}</b></p>
    <p>Email: <b>{{ user_obj.email }}</b></p>
    <p>About user: <b>{{ user_obj.profile.about_user }}</b></p>
    <p>Link to Git profile: <b><a href="">{{ user_obj.profile.git_profile }}</a></b></p>
{% endblock %}

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Update profile</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Change password: <b>{{ user_obj.username }}</b></h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text='Save' %}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit</a></li>
    <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Profile</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}"
             width="250" height="250" alt="user picture">
    {% endif %}
    <p>Username: <b>{{ user_obj.username }}</b></p>
    <p>First name: <b>{{ user_obj.first_name }}</b></p>
    <p>Last name: <b>{{ user_obj.last_name }}</b></p>
    <p>Email: <b>{{ user_obj.email }}</b></p>
    <p>About user: <b>{{ user_obj.profile.about_user }}</b></p>
    <p>Link to Git profile: <b><a href="">{{ user_obj.profile.git_profile }}</a></b></p>
{% endblock %}

source/accounts/templates/user_error.html
{% extends "base.html" %}
{% block menu %}
    <li><a href="{% url 'accounts:users_list' %}">Users</a></li>
{% endblock %}
{% block title %}{% endblock %}
{% block content %}
    <h1>Cannot do anything to this task, because you are not the project user</h1>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
    <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Edit Profile: <b>{{ user_obj.username }}</b></h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post"
    enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Update' %}
    </form>
{% endblock %}