source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api.views import ProjectViewSet, TaskViewSet, LogoutView

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet)
router.register(r'tasks', TaskViewSet)



app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='obtain_token_auth'),
    path('logout/', LogoutView.as_view(), name='delete_auth-token'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, TaskView, TaskCreateView, TaskUpdateView, \
    TaskDeleteView, StatusesView, StatusCreateView, StatusUpdateView, StatusDeleteView, TypesView, TypeCreateView, \
    TypeUpdateView, TypeDeleteView, ProjectsView, ProjectView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView,\
    TeamDeleteView, ProjectUsersUpdateView

urlpatterns = [
    path('', ProjectsView.as_view(), name='index'),
    path('tasks/', IndexView),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('task/add-project/<int:pk>/', TaskCreateView.as_view(), name='task_add'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('status/', StatusesView.as_view(), name='statuses_view'),
    path('status/add/', StatusCreateView.as_view(), name='status_add'),
    path('status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update'),
    path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='status_delete'),
    path('type/', TypesView.as_view(), name='types_view'),
    path('type/add/', TypeCreateView.as_view(), name='type_add'),
    path('type/<int:pk>/update/', TypeUpdateView.as_view(), name='type_update'),
    path('type/<int:pk>/delete/', TypeDeleteView.as_view(), name='type_delete'),
    path('projects/', ProjectsView.as_view(), name='projects_view'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/update-users/', ProjectUsersUpdateView.as_view(), name='project_users_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('user_delete/<int:pk>/', TeamDeleteView.as_view(), name='user_delete_from_project'),
]


app_name = 'webapp'

source/accounts/models.py
from django.db import models
from uuid import uuid4
from django.contrib.auth.models import User


class Token(models.Model):
    token = models.UUIDField(verbose_name='token', default=uuid4)
    user = models.ForeignKey('auth.User', related_name='registration_tokens',
                             verbose_name='User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.token)


class Team(models.Model):
    user_key = models.ForeignKey('auth.User', related_name='team', on_delete=models.PROTECT)
    project_key = models.ForeignKey('webapp.Project', related_name='team', on_delete=models.PROTECT)
    started_at = models.DateField(null=True, blank=True, verbose_name='Started at')
    ended_at = models.DateField(null=True, blank=True, verbose_name='Ended at')

    def __str__(self):
        return str(self.user_key)


class Profile(models.Model):
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    about_user = models.TextField(null=True, blank=True, verbose_name='О себе')
    git_profile = models.URLField(null=True, blank=True, verbose_name='Ссылка на Git профиль')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models
PROJECT_STATUS = (
    ('active', 'active'),
    ('blocked', 'blocked'),
)


def get_admin():
    return User.objects.get(username='admin').id


class Project(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Название проекта')
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    project_status = models.CharField(max_length=20, verbose_name='Статус проекта', choices=PROJECT_STATUS, default=PROJECT_STATUS[0][0])

    def __str__(self):
        return self.name


class Task(models.Model):
    summary = models.CharField(max_length=50, null=False, blank=False, verbose_name='краткое изложение')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='описание')
    status = models.ForeignKey('webapp.Status', related_name='task_status', on_delete=models.PROTECT, null=True, blank=True, verbose_name='статус')
    type = models.ForeignKey('webapp.Type', related_name='task_type', on_delete=models.PROTECT, null=True, blank=True, verbose_name='тип')
    project = models.ForeignKey('webapp.Project', related_name='projects_task', on_delete=models.PROTECT, null=True, blank=False, verbose_name='проект')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    created_by = models.ForeignKey(User, max_length=40, null=True, blank=True, on_delete=models.PROTECT,
                               default=get_admin, verbose_name='Author', related_name='task_creator')
    assigned_to = models.ForeignKey(User, max_length=40, null=True, blank=True, on_delete=models.PROTECT,
                               default=get_admin, verbose_name='Assigned to', related_name='task_executor')

    def __str__(self):
        return self.summary


class Type(models.Model):
    type = models.CharField(max_length=50, verbose_name='тип')

    def __str__(self):
        return self.type


class Status(models.Model):
    status = models.CharField(max_length=50, verbose_name='статус')

    def __str__(self):
        return self.status

source/webapp/forms.py
from django import forms
from accounts.models import Team
from webapp.models import Status, Type, Task, Project

from django.contrib.auth.models import User


class TeamForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = ['project_key', 'user_key', 'started_at', 'ended_at']


class ProjectForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.all_users = kwargs.pop('project_users')
        super().__init__(*args, **kwargs)
        self.fields['project_users'] = forms.ModelMultipleChoiceField(queryset=self.all_users, initial=self.initial.get('team'))

    class Meta:
        model = Project
        fields = ['name', 'description', 'project_status']


class TaskForm(forms.ModelForm):
    def __init__(self, project, **kwargs):
        super().__init__(**kwargs)
        teams = Team.objects.filter(project_key=project)
        users = []
        for team in teams:
            users.append(team)
        self.fields['assigned_to'].queryset = User.objects.filter(
            username__in=users
        )

    # def clean_assigned_to(self):
    #     super().clean()
    #     assigned_to = self.cleaned_data.get('assigned_to')
    #     project = self.cleaned_data.get('project')
    #     print(project)
    #     try:
    #         User.objects.get(username=assigned_to)
    #         return assigned_to
    #     except User.DoesNotExist:
    #         raise ValidationError('Пользователь не существует!')

    class Meta:
        model = Task
        fields = ['summary', 'description', 'status', 'type', 'assigned_to']


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']


class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = ['type']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Search')


class TeamUpdateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['team_users'] = forms.ModelMultipleChoiceField(queryset=User.objects.all(),
                                                                   initial=self.initial.get('team'))

source/webapp/views/base_views.py
from django.views import View
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render, redirect


class ListView(TemplateView):
    context_key = 'objects'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.model.objects.all()
        return context


class DetailView(TemplateView):
    context_key = 'object'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = get_object_or_404(self.model, pk=kwargs['pk'])
        return context


# class UpdateView(View):
#     form_class = None
#     template_name = None
#     redirect_url = ''
#     model = None
#     pk_kwargs_url = 'pk'
#     context_object_name = None
#     object = None
#
#     def get(self, request, *args, **kwargs):
#         obj = self.get_object()
#         form = self.form_class(instance=obj)
#         return render(request, self.template_name, context={'form': form, self.context_object_name: obj})
#
#     def post(self, request, *args, **kwargs):
#         obj = self.get_object()
#         form = self.form_class(instance=obj, data=request.POST)
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)
#
#     def get_redirect_url(self):
#         return self.redirect_url
#
#     def form_valid(self, form):
#         self.object = self.get_object()
#         form.save()
#         return redirect(self.get_redirect_url())
#
#     def form_invalid(self, form):
#         return render(self.request, self.template_name, context={'form': form})
#
#     def get_object(self):
#         pk = self.kwargs.get(self.pk_kwargs_url)
#         obj = get_object_or_404(self.model, pk=pk)
#         return obj
#
#
class DeleteView(View):
    template_name = None
    redirect_url = ''
    model = None
    pk_kwargs_url = 'pk'
    context_object_name = None
    object = None
    error_page = None

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        return render(request, self.template_name, context={self.context_object_name: object})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.project_status = 'blocked'
        self.object.save()
        return redirect(self.get_redirect_url())

    def get_object(self):
        pk = self.kwargs.get(self.pk_kwargs_url)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def get_redirect_url(self):
        return self.redirect_url

source/webapp/views/status_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from webapp.forms import StatusForm

from webapp.models import Status, Type
from django.views.generic import CreateView, UpdateView, DeleteView
from .base_views import ListView


class StatusesView(ListView):
    template_name = 'status/statuses.html'
    model = Status
    context_key = 'statuses'


class StatusCreateView(CreateView):
    model = Status
    template_name = 'status/create_status.html'
    form_class = StatusForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:statuses_view')


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'status/status_update.html'
    form_class = StatusForm
    context_object_name = 'status'

    def get_success_url(self):
        return reverse('webapp:statuses_view')


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'status/status_delete.html'
    context_object_name = 'status'
    pk_kwargs_url = 'pk'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get(self.pk_kwargs_url)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return redirect('webapp:statuses_view')
        except:
            return render(request, 'error.html')

source/webapp/views/type_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy

from webapp.forms import TypeForm

from webapp.models import Type
from django.views.generic import CreateView, UpdateView, DeleteView
from .base_views import ListView


class TypesView(ListView):
    template_name = 'type/types.html'
    model = Type
    context_key = 'types'


class TypeCreateView(CreateView):
    model = Type
    template_name = 'type/create_type.html'
    form_class = TypeForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:types_view')


class TypeUpdateView(LoginRequiredMixin, UpdateView):
    model = Type
    template_name = 'type/type_update.html'
    form_class = TypeForm
    context_object_name = 'type'

    def get_success_url(self):
        return reverse('webapp:types_view')


class TypeDeleteView(LoginRequiredMixin, DeleteView):
    model = Type
    template_name = 'type/type_delete.html'
    context_object_name = 'type'
    pk_kwargs_url = 'pk'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get(self.pk_kwargs_url)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return redirect('webapp:types_view')
        except:
            return render(request, 'error_type.html')

source/webapp/templates/project/change_project_members.html
{% extends 'base.html' %}
{% block title %}Create task{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:projects_view' %}">Projects</a></li>
{% endblock %}
{% block content %}
    <h1>Create Task</h1>
    <form method="POST" action="{% url 'webapp:project_users_update' project.pk %}">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/project/create.html
{% extends 'base.html' %}
{% block title %}Create project{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:projects_view' %}">Projects</a></li>
{% endblock %}
{% block content %}
    <h1>Create project</h1>
    <form method="POST" action="{% url 'webapp:project_add' %}">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/project/delete.html
{% extends "base.html" %}
{% block title %}Delete project{% endblock %}
{% block content %}
    <h1>Are you sure want to delete project "{{ project }}"?</h1>
    <form method="POST" action="{% url "webapp:project_delete" project.pk %}" class="text-center" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm" class="btn btn-danger"></p>
        <p><a href="{% url 'webapp:projects_view' %}" class="btn btn-default">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/project/list.html
{% extends 'base.html' %}
{% block menu %}
    {% if perms.webapp.add_project %}
        <li><a href="{% url 'webapp:project_add' %}">Add project</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1 class="mt-3">Projects</h1>
    {% include 'partial/simple_search.html' %}
    <hr>
        {% if is_paginated  %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <hr/>
    <div class="row">
        {% for project in projects %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-3">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'webapp:project_view' project.pk %}"><h2 class="card-text card-link">
                            {{ project.name }}
                        </h2></a>
                        {% if perms.webapp.add_project %}
                            <a href="{% url 'webapp:project_update' project.pk %}"><i class="fas fa-edit"></i></a>
                        {% elif perms.webapp.change_project %}
                            <a href="{% url 'webapp:project_delete' project.pk %}"><i class="fas fa-trash"></i></a>
                        {% endif %}
                        <p class="card-text">{{ project.get_category_display }}</p>
                        <p class="card-text text-right"><b>Description: </b>{{ project.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
          {% if is_paginated  %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/project/project.html
{% extends 'base.html' %}
{% block title %}{{ project.name }}{% endblock %}

{% block menu %}
    {% if perms.webapp.change_project %}
        <li><a href="{% url 'webapp:project_update' project.pk %}">Edit</a></li>
    {% elif perms.webapp.delete_project %}
        <li><a href="{% url 'webapp:project_delete' project.pk %}">Delete</a></li>
    {% elif perms.webapp.add_project%}
        <li><a href="{% url 'webapp:project_add' %}">Create</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>{{ project.name }}</h1>
    <div class="pre"><p><b>Description: </b>{{ project.description }}</p></div>
    <p><b>Status: </b>{{ project.project_status }}</p>
    <p><b>Created at: </b>{{ project.created_at|date:'d.m.Y H:i:s' }}</p>
     <p><b>Updated at: </b> {{ project.updated_at|date:'d.m.Y H:i:s' }}</p>
    <p>Projects users: </p>
    {% for user_in_team in project_team %}
        <li class="clearfix border-bottom">
            {{ user_in_team }}
            <span class="float-right">
                <form action="{% url 'webapp:user_delete_from_project'  user_in_team.pk %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </span>
        </li>
    {% endfor %}
    <hr>
    {% if perms.webapp.change_team %}
    <li><a href="{% url 'webapp:project_users_update' project.pk %}"><b>Change team members</b></a></li>
    {% endif %}
    <hr/>
    <h3>Projects tasks</h3>
    <a href="{% url 'webapp:task_add' project.pk %}"><i class="fas fa-plus-square"></i></a>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="task-list">
        {% for task in project.projects_task.all %}
            <hr>
            <div class="task">
                <p>{{ task.summary }} created at {{ task.created_at|date:'d.m.Y H:i:s' }}, created_by <b>{{ task.created_by }}</b></p>
                <div class="pre">{{ task.description }}</div>
                <a href="{% url 'webapp:task_update' task.pk %}"><i class="fas fa-edit"></i></a>
                <a href="{% url 'webapp:task_delete' task.pk %}"><i class="fas fa-trash"></i></a>
            </div>
            <hr>
        {% empty %}
            <p>No tasks yet.</p>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/project/update.html
{% extends "base.html" %}
{% block title %}Update project{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:projects_view' %}">Projects</a></li>
{% endblock %}
{% block content %}
    <h1>Update Project</h1>
    <form method="POST" action="{% url "webapp:project_update" project.pk %}">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}